name: openfile backend

on:
  push:
    branches:
      - dev-new

jobs:
  build:
    name: Build our application
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      # Cache Bun installation
      - name: Cache Bun
        id: cache-bun
        uses: actions/cache@v3
        with:
          path: ~/.bun
          key: ${{ runner.os }}-bun-${{ hashFiles('**/bunfig.toml') }}
          restore-keys: |
            ${{ runner.os }}-bun-
      
      # Install Bun if it's not cached
      - name: Install Bun
        run: |
          if [ ! -d "$HOME/.bun" ]; then
          curl -fsSL https://bun.sh/install | bash
          fi
          echo "$HOME/.bun/bin" >> $GITHUB_PATH
        continue-on-error: true # Allows the workflow to continue even if Bun is already installed

      - name: Install dependencies
        run: bun install
      
      # Write .env file
      - name: Write .env file
        run: echo "${{ secrets.ENV_FILE }}" > .env
        
        # Run migrations
      # - name: Prisma migrate
      #   run: bunx prisma migrate dev --name updated_model

      # - name: Generate Prisma Client
      #   run: bunx prisma generate
      
      # - name: Push Prisma schema to DB
      #   run: bunx prisma db push

      - name: Run tests
        run: bun run test --timeout=20000
        