services:
  # redis:
  #   image: redis
  #   ports:
  #     - "6379:6379"
  #   restart: unless-stopped
  #   volumes:
  #     - redis_data:/data

  backend:
    build: .
    ports:
      - "8000:8000"
      
    environment:
      - PORT=${PORT}
      - DATABASE_URL=${DATABASE_URL}
      - JWT_SECRET=${JWT_SECRET}
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
      
      - ACCESS_TOKEN_SECRET=${ACCESS_TOKEN_SECRET}
      - ACCESS_TOKEN_EXPIRY=${ACCESS_TOKEN_EXPIRY}
      - REFRESH_TOKEN_SECRET=${REFRESH_TOKEN_SECRET}
      - REFRESH_TOKEN_EXPIRY=${REFRESH_TOKEN_EXPIRY}
      
      - MAILER_TYPE=${MAILER_TYPE}
      - MAIL_SERVICE=${MAIL_SERVICE}
      - MAIL_USER=${MAIL_USER}
      - MAIL_PASS=${MAIL_PASS}
      - RESEND_API_KEY=${RESEND_API_KEY}
      
      - NODE_ENV=${NODE_ENV}
      - PRODUCTION=${PRODUCTION}
      - APP_URL=${APP_URL}
      
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_REGION=${AWS_REGION}
      - AWS_BUCKET=${AWS_BUCKET}
      - UPLOAD_URL=${UPLOAD_URL}

      - REDIS_CLOUD_PASS=${REDIS_CLOUD_PASS}
      - REDIS_CLOUD_HOST=${REDIS_CLOUD_HOST}
      - REDIS_CLOUD_PORT=${REDIS_CLOUD_PORT}
      - REDIS_PASS=${REDIS_PASS}
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
      - REDIS_URL=${REDIS_URL}

      - STORAGE_TYPE=${STORAGE_TYPE}
      - CLOUDFLARE_BUCKET=${CLOUDFLARE_BUCKET}
      - CLOUDFLARE_ACCOUNT_ID=${CLOUDFLARE_ACCOUNT_ID}
      - CLOUDFLARE_ACCESS_KEY=${CLOUDFLARE_ACCESS_KEY}
      - CLOUDFLARE_SECRET_KEY=${CLOUDFLARE_SECRET_KEY}
      - CLOUDFLARE_REGION=${CLOUDFLARE_REGION}
      - CLOUDFLARE_TOKEN_VALUE=${CLOUDFLARE_TOKEN_VALUE}

      - DODO_PAYMENTS_API_KEY=${DODO_PAYMENTS_API_KEY}
      - DODO_PAYMENTS_WEBHOOK_KEY=${DODO_PAYMENTS_WEBHOOK_KEY}
      - DODO_PAYMENTS_ENVIRONMENT=${DODO_PAYMENTS_ENVIRONMENT}
      - DODO_PAYMENTS_RETURN_URL=${DODO_PAYMENTS_RETURN_URL}
    # depends_on:
    #   - redis

volumes:
  redis_data: