/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/auth` | `/auth`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/create-link` | `/create-link`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/links` | `/links`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}${'/(profile)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `/link/[id]`, params: Router.UnknownInputParams & { id: string | number; } };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(auth)'}/auth` | `/auth`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/create-link` | `/create-link`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/links` | `/links`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}${'/(profile)'}` | `/`; params?: Router.UnknownOutputParams; } | { pathname: `/link/[id]`, params: Router.UnknownOutputParams & { id: string; } };
      href: Router.RelativePathString | Router.ExternalPathString | `/${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(auth)'}/auth${`?${string}` | `#${string}` | ''}` | `/auth${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/create-link${`?${string}` | `#${string}` | ''}` | `/create-link${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/links${`?${string}` | `#${string}` | ''}` | `/links${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}${'/(profile)'}${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/auth` | `/auth`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/create-link` | `/create-link`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/links` | `/links`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}${'/(profile)'}` | `/`; params?: Router.UnknownInputParams; } | `/link/${Router.SingleRoutePart<T>}${`?${string}` | `#${string}` | ''}` | { pathname: `/link/[id]`, params: Router.UnknownInputParams & { id: string | number; } };
    }
  }
}
