name: Deploy to ec2

on:
  push:
    branches:
      - main

jobs:
   deploy:
      runs-on: ubuntu-latest
      
      steps:
        - name: Deploy to the server
          uses: appleboy/ssh-action@v1.0.3
          with:
             host: ${{ secrets.EC2_HOST }}
             username: ${{ secrets.EC2_USER }}
             key: ${{ secrets.EC2_SSH_KEY_OPENFILE }}
             script: |
               cd openfile.in
               git fetch origin
               git reset --hard origin/main
               cd apps/backend
               chmod +x ./pm2.sh
               ./pm2.sh
              #  docker compose -f apps/backend/compose.yml up --build -d
               