name: "Deploy Web on VPS"

on:
  push:
    branches:
      - main
    paths:
      - "apps/frontend/**"
      - "package.json"
      - "bun.lock"
      - ".github/workflows/web-cd.yml"

concurrency:
  group: deploy-web
  cancel-in-progress: true

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Install dependencies & Build Frontend
        env:
          VITE_BACKEND_APP_URL: ${{ secrets.VITE_BACKEND_APP_URL }}
          VITE_DODO_PRODUCT_ID: ${{ secrets.VITE_DODO_PRODUCT_ID }}
          VITE_GOOGLE_CLIENT_ID: ${{ secrets.VITE_GOOGLE_CLIENT_ID }}
          VITE_MAX_FREE_USER_UPLOAD_MB: ${{ secrets.VITE_MAX_FREE_USER_UPLOAD_MB }}
          VITE_PRODUCTION: ${{ secrets.VITE_PRODUCTION }}
          VITE_UPLOAD_URL: ${{ secrets.VITE_UPLOAD_URL }}
        run: |
          cd apps/frontend
          bun install --frozen-lockfile
          bun run build

      - name: Update git codebase on VPS
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          password: ${{ secrets.VPS_PASSWORD }}
          script: |
            set -e
            echo "[Frontend] Pulling latest codebase..."
            cd /srv/apps/openfile.in
            git fetch origin
            git reset --hard origin/main

      - name: Upload build output to VPS
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          password: ${{ secrets.VPS_PASSWORD }}
          source: "apps/frontend/build/client"
          target: "/srv/apps/openfile.in/apps/frontend"
          strip_components: 2



